server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10m

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
    instances:
      evaluate:
        registerHealthIndicator: true
        failureRateThreshold: 5
        waitDurationInOpenState: 1s
        slidingWindowSize: 2

resilience4j.timelimiter:
    instances:
      evaluate:
        timeoutDuration: 400ms
        cancelRunningFuture: true
