spring:
  application:
    name: circuit-breaker-pattern

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        register-health-indicator: true
        failure-rate-threshold: 50 # 실패율 임계값 (50%)
        minimum-number-of-calls: 5 # 최소 호출 횟수
        sliding-window-size: 10 # 슬라이딩 윈도우 크기
        wait-duration-in-open-state: 5s # Open 상태에서 Half-Open 상태로 전환하기까지 대기 시간
        permitted-number-of-calls-in-half-open-state: 3 # Half-Open 상태에서 허용되는 호출 횟수
