spring:
  application:
    name: spring-retry-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enterprise?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    hikari:
      username: root
      password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
